### ISSUE TITLE
Give a description of what the app is meant to offer

### ISSUE THREAD

**Issue by Ollie-Wan** [cforlando/orlando-walking-tours-android#1]
I read on the iOS readme that the app will _allow users to create customized walking tours of the various historic locations around the city of Orlando_. Would it be possible to write somewhere what needs to be done? Is the prototype up to date? And is there a list of "requirement" so we can start working on it or a more detailed description of the app. (I suppose it's linked to https://github.com/cforlando/orlando-walking-tours-ios/issues/39 from the iOS repo)

**Comment by fatdzo** [comment]
We had a meeting yesterday where we discussed the look, feel and the features of the app. The iOS app is also being redone, I think @WERUreo has transitioned the application to swift . 

At this moment, we are waiting for the mockups. Once we have those, the plan is to split and organize the work that needs to be done.
