### ISSUE TITLE
Investigate Travis Build issues

### ISSUE THREAD

**Issue by fatdzo** [cforlando/orlando-walking-tours-android#26]
Currently, Travis will not build API 23 of the android project. Investigate.

**Comment by Ollie-Wan** [comment]
I looked into that, there is a PR here: https://github.com/cforlando/orlando-walking-tours-android/pull/29 if you guys want to take a look.

**Comment by fatdzo** [comment]
Accepted the pull request, I had to update  to AppCompatActivity on MainActivity.js because the build was failing.

Thanks.
