### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by Ollie-Wan** [cforlando/orlando-walking-tours-android#30]
Before we got too much going on, shouldn't we rename the package to be `com.codefororlando.walkingtours` instead of  `com.example.cforlando.walkingtours`?

**Comment by fatdzo** [comment]
Sounds like a good idea.

**Comment by akozlik** [comment]
That works. We need to set up an apple developer account too.

**Comment by devdupont** [comment]
Should I take care of that?

**Comment by akozlik** [comment]
I'll take care of it. We need to make a purchase and file it through CFA.

**Comment by fatdzo** [comment]
@akozlik  Do we have an Google developer account for cfo? We will need it for the Android app.

**Comment by akozlik** [comment]
We do not. My plan was to set up both at the same time. I'll take care of that this week and make Michael an admin on both.

**Comment by WERUreo** [comment]
Just for reference, the iOS bundle identifier is com.codefororlando.Orlando-Walking-Tours.

**Comment by Ollie-Wan** [comment]
Cool, Thanks @WERUreo. Let's be consistent.

**Comment by fatdzo** [comment]
package names should all be lowercase if I remember correctly

**Comment by Ollie-Wan** [comment]
:+1:  Good catch I didn't notice it wasn't; but you are correct, at least in java.
