### ISSUE TITLE
Integrate with Firebase

### ISSUE THREAD

**Issue by WERUreo** [cforlando/orlando-walking-tours-android#50]
There is a Firebase project for Walking Tours that has been created and is being used by the iOS app currently.  We would need to get the Android app integrated with Firebase as well.

**Comment by quicodesfor** [comment]
Taking this issue

**Comment by quicodesfor** [comment]
@WERUreo Can you make the Firebase landmark data public and post the access info?

**Comment by quicodesfor** [comment]
If anyone wants to integrate Firebase, I suggest you start fresh. Firebase database is very opinionated NoSQL which is a drastic deviation from Android SQLite. I don't even know if there are articles or "courses" which promote Firebase database and goes against the guidelines specified in the README about keeping with maintainable patterns. If you would like to introduce/integrate Firebase, I would recommend starting with authentication and then moving beyond. As always, fork or branch first.
